/**
 * Single source of truth for chain + contract wiring.
 *
 * Generated by Member 1's deploy script and synced into integration/machinapay.contracts.json.
 */
import raw from "../../integration/machinapay.contracts.json";

export interface MachinaPayConfig {
  network: string;
  chainId: number;
  rpcUrl: string;
  explorerUrl: string | null;
  nativeToken: string;
  addresses: { MachineRegistry: string; JobEscrow: string };
  verifier: string;
  eip712: { name: string; version: string; chainId: number; verifyingContract: string };
  abi: { MachineRegistry: any[]; JobEscrow: any[] };
}

export const cfg = raw as unknown as MachinaPayConfig;
export const NATIVE_SYMBOL = cfg.nativeToken || "ETH";

export function getContractConfig() {
  return {
    rpcUrl: cfg.rpcUrl,
    chainId: cfg.chainId,
    network: cfg.network,
    escrowAddress: cfg.addresses.JobEscrow,
    registryAddress: cfg.addresses.MachineRegistry,
    escrowAbi: cfg.abi.JobEscrow,
    registryAbi: cfg.abi.MachineRegistry,
    verifier: cfg.verifier,
  };
}

// Member 3's backend service base URL (see Backend-service/README.md).
// Override with VITE_MEMBER3_API_URL in a .env file for a deployed backend.
export const MEMBER3_API_URL =
  (import.meta as any).env?.VITE_MEMBER3_API_URL || "http://localhost:4000";

// Machine IDs to show in the UI if not fetched dynamically from the registry contract
export const DEFAULT_MACHINE_IDS: string[] = (
  (import.meta as any).env?.VITE_MACHINE_IDS
    ? String((import.meta as any).env.VITE_MACHINE_IDS).split(",").map((s) => s.trim()).filter(Boolean)
    : ["M-042"]
);

// Fallback demo target until Member 2's robot simulation is wired up
export const DEFAULT_EVIDENCE_TARGET = {
  packageId: (import.meta as any).env?.VITE_DEFAULT_PACKAGE_ID || "A",
  target: {
    zone: (import.meta as any).env?.VITE_DEFAULT_TARGET_ZONE || "green",
    x: Number((import.meta as any).env?.VITE_DEFAULT_TARGET_X ?? 9),
    y: Number((import.meta as any).env?.VITE_DEFAULT_TARGET_Y ?? 4),
  },
};

// Default form inputs for posting demo jobs
export const DEFAULT_JOB_CONFIG = {
  description: (import.meta as any).env?.VITE_DEFAULT_JOB_DESCRIPTION || "Move package A to green zone",
  reward: (import.meta as any).env?.VITE_DEFAULT_JOB_REWARD || "100",
  minutes: (import.meta as any).env?.VITE_DEFAULT_JOB_MINUTES || "60",
};

export const JOB_STATE_NAMES = [
  "CREATED", "FUNDED", "ACCEPTED", "EXECUTING",
  "PROOF_SUBMITTED", "VERIFIED", "PAID", "REFUNDED",
] as const;

export const VERDICT_NAMES = ["NONE", "PASS", "FAIL"] as const;
