/**
 * Single source of truth for chain + contract wiring.
 *
 * Generated by Member 1's deploy script and synced into integration/machinapay.contracts.json.
 */
import rawContracts from "../../integration/machinapay.contracts.json";

export interface MachinaPayConfig {
  network: string;
  chainId: number;
  rpcUrl: string;
  explorerUrl: string | null;
  nativeToken: string;
  addresses: { MachineRegistry: string; JobEscrow: string };
  verifier: string;
  eip712: { name: string; version: string; chainId: number; verifyingContract: string };
  abi: { MachineRegistry: any[]; JobEscrow: any[] };
}

const networkMode = (import.meta as any).env?.VITE_NETWORK_MODE || "mst";
const isLocal = networkMode === "local" || networkMode === "localhost";

const mstRpc = (import.meta as any).env?.VITE_MST_RPC_URL || "https://testnetrpc.mstblockchain.com";
const mstChainId = Number((import.meta as any).env?.VITE_MST_CHAIN_ID || 91562037);
const mstExplorer = (import.meta as any).env?.VITE_MST_EXPLORER_URL || "https://testnet.mstscan.com";

const envRegistry = (import.meta as any).env?.VITE_MACHINE_REGISTRY_ADDRESS;
const envEscrow = (import.meta as any).env?.VITE_JOB_ESCROW_ADDRESS;

export const cfg: MachinaPayConfig = {
  network: isLocal ? (rawContracts.network || "localhost") : "MST Testnet",
  chainId: isLocal ? Number(rawContracts.chainId || 31337) : mstChainId,
  rpcUrl: isLocal ? (rawContracts.rpcUrl || "http://127.0.0.1:8545") : mstRpc,
  explorerUrl: isLocal ? rawContracts.explorerUrl : mstExplorer,
  nativeToken: isLocal ? "MSTC" : "tMSTC",
  addresses: {
    MachineRegistry: envRegistry || rawContracts.addresses?.MachineRegistry || "0x0000000000000000000000000000000000000000",
    JobEscrow: envEscrow || rawContracts.addresses?.JobEscrow || "0x0000000000000000000000000000000000000000",
  },
  verifier: rawContracts.verifier || "0x5C024AF5878888a9F1d4E1aAfF6a928DEc812225",
  eip712: {
    name: "MachinaPay JobEscrow",
    version: "1",
    chainId: isLocal ? Number(rawContracts.chainId || 31337) : mstChainId,
    verifyingContract: envEscrow || rawContracts.addresses?.JobEscrow || "0x0000000000000000000000000000000000000000",
  },
  abi: rawContracts.abi as any,
};

// Centralized native token symbol
export const NATIVE_SYMBOL = cfg.nativeToken || "tMSTC";

// Dynamic pricing scale factor (default 0.1 for the demo so 22 & 35 units scale to 2.2 and 3.5 MSTC)
export const PRICE_SCALE = Number((import.meta as any).env?.VITE_PRICE_SCALE || 0.1);

export function getContractConfig() {
  return {
    rpcUrl: cfg.rpcUrl,
    chainId: cfg.chainId,
    network: cfg.network,
    escrowAddress: cfg.addresses.JobEscrow,
    registryAddress: cfg.addresses.MachineRegistry,
    escrowAbi: cfg.abi.JobEscrow,
    registryAbi: cfg.abi.MachineRegistry,
    verifier: cfg.verifier,
  };
}

// Member 3's backend service base URL (see Backend-service/README.md).
// Override with VITE_MEMBER3_API_URL in a .env file for a deployed backend.
export const MEMBER3_API_URL =
  (import.meta as any).env?.VITE_MEMBER3_API_URL || "http://localhost:4000";

// Standalone 3D machine console, linked from the live Wallet Map.
export const SIMULATOR_URL =
  (import.meta as any).env?.VITE_SIMULATOR_URL || "http://localhost:5174";

// Machine IDs to show in the UI if not fetched dynamically from the registry contract
export const DEFAULT_MACHINE_IDS: string[] = (
  (import.meta as any).env?.VITE_MACHINE_IDS
    ? String((import.meta as any).env.VITE_MACHINE_IDS).split(",").map((s) => s.trim()).filter(Boolean)
    : ["M-042", "M-051"]
);

// Fallback demo target until Member 2's robot simulation is wired up
export const DEFAULT_EVIDENCE_TARGET = {
  packageId: (import.meta as any).env?.VITE_DEFAULT_PACKAGE_ID || "A",
  target: {
    zone: (import.meta as any).env?.VITE_DEFAULT_TARGET_ZONE || "green",
    x: Number((import.meta as any).env?.VITE_DEFAULT_TARGET_X ?? 9),
    y: Number((import.meta as any).env?.VITE_DEFAULT_TARGET_Y ?? 4),
  },
};

// Default form inputs for posting demo jobs
export const DEFAULT_JOB_CONFIG = {
  description: (import.meta as any).env?.VITE_DEFAULT_JOB_DESCRIPTION || "Move package A to green zone",
  reward: (import.meta as any).env?.VITE_DEFAULT_JOB_REWARD || "2.2",
  minutes: (import.meta as any).env?.VITE_DEFAULT_JOB_MINUTES || "60",
};

export const JOB_STATE_NAMES = [
  "CREATED", "FUNDED", "ACCEPTED", "EXECUTING",
  "PROOF_SUBMITTED", "VERIFIED", "PAID", "REFUNDED",
] as const;

export const VERDICT_NAMES = ["NONE", "PASS", "FAIL"] as const;
